version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
    depends_on:
      - database
    restart: always
    container_name: hack-server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hack-client
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    
  database:
    image: postgres:12.2-alpine
    restart: "no"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: hack-database
    ports:
      - '5000:5000'
  
  databaseadmin:
    image: dpage/pgadmin4
    container_name: hack-database-admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"